name: 'Project Automator'
description: 'Automates project boards.'
author: 'moderndocmedia'
inputs:
  ghToken:
    description: "A GitHub Personal Access Token"
    required: true
  projectNumber:
    description: "The number of the project with issues. Get this from the URL."
    required: true
  overviewProjectNumber:
    description: "The number of the overview project to sync."
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'